<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="run on firefox"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="24.624">
  <properties />
            <testcase name="Employee_01_Add_New_Employee" time="8.808" classname="com.hrm.employee.Level_21_Data_Driven_II">
                <failure type="java.lang.AssertionError"
                  message="expected:&lt;0258&gt; but was:&lt;0259&gt;"
              >
<![CDATA[java.lang.AssertionError: expected:<0258> but was:<0259>
  org.testng.AssertJUnit.fail(AssertJUnit.java:59)
  org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
  org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
  org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
  commons.BaseTest.checkEquals(BaseTest.java:126)
  commons.BaseTest.verifyEquals(BaseTest.java:138)
  com.hrm.employee.Level_21_Data_Driven_II.Employee_01_Add_New_Employee(Level_21_Data_Driven_II.java:139)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  java.base/java.lang.Thread.run(Thread.java:832)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="Employee_02_Upload_Avatar" time="8.809" classname="com.hrm.employee.Level_21_Data_Driven_II" />
                <testcase name="Employee_03_Personal_Details" time="7.007" classname="com.hrm.employee.Level_21_Data_Driven_II" />
      
</testsuite>
