<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NGOC-THY-PC" failures="1" tests="3" name="com.hrm.employee.Level_21_Data_Driven_II" time="24.624" errors="0" timestamp="10 Oct 2021 08:00:24 GMT">
  <testcase classname="com.hrm.employee.Level_21_Data_Driven_II" name="Employee_02_Upload_Avatar" time="8.809"/>
  <testcase classname="com.hrm.employee.Level_21_Data_Driven_II" name="Employee_01_Add_New_Employee" time="8.808">
    <failure message="expected:&lt;0258&gt; but was:&lt;0259&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<0258> but was:<0259>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
	at commons.BaseTest.checkEquals(BaseTest.java:126)
	at commons.BaseTest.verifyEquals(BaseTest.java:138)
	at com.hrm.employee.Level_21_Data_Driven_II.Employee_01_Add_New_Employee(Level_21_Data_Driven_II.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- Employee_01_Add_New_Employee -->
  <testcase classname="com.hrm.employee.Level_21_Data_Driven_II" name="Employee_03_Personal_Details" time="7.007"/>
</testsuite> <!-- com.hrm.employee.Level_21_Data_Driven_II -->
